chromiumBeta: Fix the build
This "fixes" the following error:
gen/shim_headers/opus_shim/third_party/opus/src/include/opus.h:5:10: error: 'opus.h' file not found with <angled> include; use "quotes" instead
         ^~~~~~~~
         "opus.h"

Our system library isn't discovered anymore so I'm switching to the bundled
Opus library for now since I don't have time to look into it.

(cherry picked from commit 1bdf7862e3f8007cdb21bbbde1d496064f869bb3)